version: '3'
services:
  postgres:
    image: postgres:12.2
    container_name: test_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=root